### ISSUE TITLE
`str-to-num` expected behavior?

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#84]
Not sure if these are expected but doesn't seem to be consistent with name of the function:

```
(str-to-num "-20")
-280
(str-to-num "20.9")
1369702
(str-to-num "-0")
-30
```

**Comment by vygr** [comment]
This is producing a fixed point number as an int ! Yes I know this is a little 'unfinished' I been adding the polymophic number stuff to replace all this for a while, not covered all cases yet. !

**Comment by vygr** [comment]
You can even do 0x45.67 ! Hex base fixed point...

**Comment by vygr** [comment]
-0 is just plain wrong. I just didn't care about that case at the time.

**Comment by vygr** [comment]
May also find it doesn’t do negative numbers at all !

That’s just because where it first got used was for a Lisp version of the built in read_num when I did the C-Script parser and it never called it needing to handle negativity. 

But this is probably better done these days as a binding to the internal read_num routines. Which I can look at next if you want.

**Comment by FrankC01** [comment]
That would be good as a general thing. My immediate usage is to have type checking conversion of a command line arg to an integer or float (double? real?).

**Comment by nuclearfall** [comment]
Both are really hacky, but I have s2i for integers in the date lib. It handles negative integers, but it will only work on strings up to length 12 or so. I assume it's some n-bit integer constraint I hit while adding values.

I wrote s2n to handle floats, it uses s2i and i2f for all the heavy lifting but since division of 1.0 by 10.0 results in 0.09999 it doesn't quite work as desired.

```
(defun-bind s2n (s)
  (defq divisor 1)
    (cond
      ((find "." s) 
        (+ (i2f (s2i (first (split s "."))))
          (/ (i2f (s2i (defq decimal (second (split s "."))))) 
           (i2f (each (lambda (_) (setq divisor (* 10 divisor))) 
             (range 0 (length decimal)))))))
      (t (s2i s))))

**Comment by vygr** [comment]
Current `(str-to-num)` hack in boot.inc:

```lisp
(defun-bind str-to-num (_)
	;(str-to-num str) -> num
	(defq n 0 b 10)
	(when (> (length _) 1)
		(defq i (elem 1 _))
		(cond
			((eql i "x")
				(setq b 16 _ (slice 2 -1 _)))
			((eql i "o")
				(setq b 8 _ (slice 2 -1 _)))
			((eql i "b")
				(setq b 2 _ (slice 2 -1 _)))))
	(defq i -1 f 0)
	(while (< (setq i (inc i)) (length _))
		(defq c (elem i _))
		(if (eql c ".")
			(setq f 1)
			(defq d (char-to-num c) n (+ (* n b) d) f (* f b))))
	(if (= f 0) n (/ (<< n fp_shift) f)))
```

This tries to guess the base of the number, then shift in the digits in that base. If it see a '.' it remembers the position of that and turns thing into a fixed point as the last thing.

Was very quick and dirty at the time of writing. Didn't test for leading -, didn't cope with errors of any kind etc

**Comment by vygr** [comment]
Better version based on current features:

```lisp
(defun-bind str-to-num (_)
	;(str-to-num str) -> num
	(defq n 0 b 10 f 0)
	(when (> (length _) 1)
		(defq i (elem 1 _))
		(cond
			((eql i "x")
				(setq b 16 _ (slice 2 -1 _)))
			((eql i "o")
				(setq b 8 _ (slice 2 -1 _)))
			((eql i "b")
				(setq b 2 _ (slice 2 -1 _)))))
	(each (# (if (eql %0 ".")
			(setq f 1)
			(setq n (+ (* n b) (char-to-num %0)) f (* f b)))) _)
	(if (= f 0) n (/ (<< n fp_shift) f)))
```

I'll push this as it is faster ! Note the cute use of Franks (#) function shortcuts now :) That was such a good addition. :)

**Comment by vygr** [comment]
pushed a version that copes with uppercase type chars.
