### ISSUE TITLE
Provide a "your first program" or "getting started" doc

### ISSUE THREAD

**Issue by traverseda** [vygr/ChrysaLisp#9]
The programming itself is clear enough, but it's somewhat unclear how one would get started developing for ChrysaLisp.

**Comment by vygr** [comment]
Hey Alex,

Ok, to start the ball rolling on this. What sort of getting started doc ?

About Lisp in general ?
This flavor of Lisp ?
The VM register machine level assembler ?
The C-Script step up from the register level assembler ?
Writing a class library and hooking it into the Lisp ?
Maybe doing a processor back end emit file ?
First command line app ?
First GUI app ?
Adding a GUI component ?

Trick question, yes ALL of the above would be nice ! So which is priority, I'll start on something I promise, just short of spare time to do everything I'd like :) Which is why it's nice to have people who step up and do stuff, like yourself, interested :)

Chris

**Comment by vygr** [comment]
I heading off to sleep at this end just now, need my beauty sleep. You can tell that from my mug shot ;)

Chris

**Comment by traverseda** [comment]
Probably first command line app with a side helping of this flavor of lisp. From there, it should be reasonable to use the existing documentation. The tricky part is going to be getting new developers acquainted with the eco-system. Once that's in place, it should be reasonable for non-lisp developers to start hacking away at stuff.

**Comment by neauoire** [comment]
Added a basic GUI application `hello/app.lisp`, ideal to expand from and experiment with **Chrysa**.
Currently in PR: https://github.com/vygr/ChrysaLisp/pull/15

**Comment by vygr** [comment]
Think recent doc additions and demos help close this one for now.

**Comment by neauoire** [comment]
Absolutely, thanks!
There are enough examples now for anyone to get started.
